#initial login with neo4j/neo4j or use env variable NEO4J_AUTH=none to disable security (leave user and pass blank and click connect)
#use "latest" or "community" version to get community or "enterprise" to get "enterprise"

version: '3'
services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./graphdb/conf:/conf
      - ./graphdb/data:/data
      - ./graphdb/import:/import
      - ./graphdb/logs:/logs
      - ./graphdb/plugins:/plugins
    environment:
      # Raise memory limits
      - NEO4J_AUTH=none
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
  #    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes #needed only for enterprise version
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]