#from adminer user server:"age:5432", username:postgres, password:example, database: <none>

version: '3'
services:
  age:
    image: apache/age:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"

  age-viewer:
    build: ./age/viewer
    image: mmaracic/age-viewer:v1.0
    ports:
      - "8082:3001"
    stdin_open: true #required so that container wouldn't immediately exit

  age-adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"